### ISSUE TITLE
是否有针对springboot的处理

### ISSUE THREAD

**Issue by hanminqiang** [dsc-cmt/dubbo-easy-mock#1]
个人理解是在消费端pom引入即可，还需要做哪些配置吗？

**Comment by shengchaojie** [comment]
需要配置哪些接口需要走mock逻辑，以及mock服务器地址

**Comment by hanminqiang** [comment]
我的理解就是消费者出引入pom，然后配置mock.properties 即可吗？


可以配置多个RPC接口吗？


您看下是否正确 启动调用并没有走mock或者报个错之类的&nbsp; 还是直接调用的真是服务









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dsc-cmt/dubbo-easy-mock"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月4日(星期一) 中午1:33
收件人:&nbsp;"dsc-cmt/dubbo-easy-mock"<dubbo-easy-mock@noreply.github.com&gt;;
抄送:&nbsp;"木左"<1255475997@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dsc-cmt/dubbo-easy-mock] 是否有针对springboot的处理 (#1)





 
需要配置哪些接口需要走mock逻辑，以及mock服务器地址

**Comment by shengchaojie** [comment]
对的 引入依赖是强制触发的 
至于哪些接口需要mock是通过mock.properties里配置的
原理就是通过dubbo的扩展点自动包装 将请求转发了
不做配置的话 这段转发逻辑不会触发

这个框架用于集成测试/自动化测试

**Comment by hanminqiang** [comment]
配置了也没有走到mock 感觉就是没有触发的样子




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dsc-cmt/dubbo-easy-mock"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月4日(星期一) 下午3:01
收件人:&nbsp;"dsc-cmt/dubbo-easy-mock"<dubbo-easy-mock@noreply.github.com&gt;;
抄送:&nbsp;"木左"<1255475997@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dsc-cmt/dubbo-easy-mock] 是否有针对springboot的处理 (#1)





 
对的 引入依赖是强制触发的
 至于哪些接口需要mock是通过mock.properties里配置的
 原理就是通过dubbo的扩展点自动包装 将请求转发了
 不做配置的话 这段转发逻辑不会触发
 
这个框架用于集成测试/自动化测试

**Comment by hanminqiang** [comment]
已经解决 是META-INF下 dubbo的org.apache.dubbo.rpc.cluster.Cluster中easymock=com.cmt.des.EasyMockClusterWrapper的配置路径不一致  改为和工程包一致的路径即可

**Comment by shengchaojie** [comment]
> 已经解决 是META-INF下 dubbo的org.apache.dubbo.rpc.cluster.Cluster中easymock=com.cmt.des.EasyMockClusterWrapper的配置路径不一致 改为和工程包一致的路径即可

额，移动过项目，没改这里。。。我改下
